### ISSUE TITLE
counter - TODO

### ISSUE THREAD

**Issue by wookikiik** [wookikiik/angular_study#9]
- [ ] 1. router 구성
- [ ] 2. 메인 페이지로 main.component 사용 (router 연결)
- [ ] 3. 2번 lazy router로 개발
- [ ] 4. counter.service main.module 에서는 따로 작동하도록 구성
